### ISSUE TITLE
[Meta] Are we the eclipse plugin yet?

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/intelligrade#15]
We should track the features of [programming-lecture-eclipse-artemis](https://github.com/kit-sdq/programming-lecture-eclipse-artemis)

## META
- [x] Grading of normal exercises
- [x] Grading of exams with one correction round
- [x] Grading of exams with two correction rounds
- [x] Multi-Language Support (German / English)

## Details
- [x] Autograder
- [x] Show statistics (meta information)
- [x] Backlog support
- [x] Grading Button support
- [x] Overview for automatic tests
- [x] Login via Token, Username/Passoword / GIT Token
- [x] #24
- [x] Tooltip text for annotations
- [x] Mouseless Grading

**Comment by CDaut** [comment]
Note: Auto opening the main class seems to be notoriously difficult because to find the main class the PSI needs to be built and there does not seem to be a good hook.

**Comment by CDaut** [comment]
Note: Tooltip shows on the right
